version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    volumes:
      - '../app/:/app/'
    working_dir: /app
    ports:
      - 3000:3000
    command: sleep infinity